/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as HireImport } from './routes/hire'
import { Route as FreelancerProjectsImport } from './routes/freelancer-projects'
import { Route as FindProjectsImport } from './routes/find-projects'
import { Route as FinancesImport } from './routes/finances'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const HireRoute = HireImport.update({
  path: '/hire',
  getParentRoute: () => rootRoute,
} as any)

const FreelancerProjectsRoute = FreelancerProjectsImport.update({
  path: '/freelancer-projects',
  getParentRoute: () => rootRoute,
} as any)

const FindProjectsRoute = FindProjectsImport.update({
  path: '/find-projects',
  getParentRoute: () => rootRoute,
} as any)

const FinancesRoute = FinancesImport.update({
  path: '/finances',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/finances': {
      id: '/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof FinancesImport
      parentRoute: typeof rootRoute
    }
    '/find-projects': {
      id: '/find-projects'
      path: '/find-projects'
      fullPath: '/find-projects'
      preLoaderRoute: typeof FindProjectsImport
      parentRoute: typeof rootRoute
    }
    '/freelancer-projects': {
      id: '/freelancer-projects'
      path: '/freelancer-projects'
      fullPath: '/freelancer-projects'
      preLoaderRoute: typeof FreelancerProjectsImport
      parentRoute: typeof rootRoute
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/find-projects': typeof FindProjectsRoute
  '/freelancer-projects': typeof FreelancerProjectsRoute
  '/hire': typeof HireRoute
  '/profile': typeof ProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/find-projects': typeof FindProjectsRoute
  '/freelancer-projects': typeof FreelancerProjectsRoute
  '/hire': typeof HireRoute
  '/profile': typeof ProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/finances': typeof FinancesRoute
  '/find-projects': typeof FindProjectsRoute
  '/freelancer-projects': typeof FreelancerProjectsRoute
  '/hire': typeof HireRoute
  '/profile': typeof ProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finances'
    | '/find-projects'
    | '/freelancer-projects'
    | '/hire'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finances'
    | '/find-projects'
    | '/freelancer-projects'
    | '/hire'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/finances'
    | '/find-projects'
    | '/freelancer-projects'
    | '/hire'
    | '/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinancesRoute: typeof FinancesRoute
  FindProjectsRoute: typeof FindProjectsRoute
  FreelancerProjectsRoute: typeof FreelancerProjectsRoute
  HireRoute: typeof HireRoute
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinancesRoute: FinancesRoute,
  FindProjectsRoute: FindProjectsRoute,
  FreelancerProjectsRoute: FreelancerProjectsRoute,
  HireRoute: HireRoute,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/finances",
        "/find-projects",
        "/freelancer-projects",
        "/hire",
        "/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/finances": {
      "filePath": "finances.tsx"
    },
    "/find-projects": {
      "filePath": "find-projects.tsx"
    },
    "/freelancer-projects": {
      "filePath": "freelancer-projects.tsx"
    },
    "/hire": {
      "filePath": "hire.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
